### ISSUE TITLE
Not really an issue but a question

### ISSUE THREAD

**Issue by olderatriangle** [realDunkin/fnfmegapack#27]
How did you make this and port it to HTML? I already opened a discussion about this a couple of days ago and I just wanted to know how to port FNF to web browsers because I wanted to port some mods of my own to HTML.

**Comment by realDunkin** [comment]
Its pretty simple, just compile the game as usual, but instead of windows do `lime test html5` and then it'll compile the game as html5.
There are some mods that'll take more then that since something's aren't compatible for html5
After you compiled the game just put it on GitHub and turn on GitHub pages!

**Comment by olderatriangle** [comment]
Thank you very much. Also, when I was compiling Kade Engine a couple of days ago, I got Visual Studio 2019 and 2017 and installed everything that Kade said to do in his readme but when I put in rebuild extension-webm windows, it just didn't work. It didn't show anything, didn't say that it was complete or anything. Do you know what I did wrong?

**Comment by realDunkin** [comment]
You might already have a version of extension-webm rebuilt for windows

**Comment by olderatriangle** [comment]
Oh, ok.

**Comment by olderatriangle** [comment]
I tried it, and it didn't work. Here's a screenshot
![error](https://user-images.githubusercontent.com/91300048/136112661-31c2954e-7461-479a-aee1-0b65cad2713f.JPG)
.

**Comment by realDunkin** [comment]
Go to `C:/HaxeToolKit/haxe/lib/` and delete `extension-webm` then install it again see if it'll work

**Comment by olderatriangle** [comment]
I deleted it, and installed it again. Nothing happened. Then I went to power shell and I got the same ndll error.
![Capture](https://user-images.githubusercontent.com/91300048/136116435-ae1ebae5-d1cf-48fb-8d39-feb8018f1d5a.JPG)

**Comment by olderatriangle** [comment]
It even says I installed it after I deleted it.
![Capture4](https://user-images.githubusercontent.com/91300048/136116539-b20f7512-cc4d-4b8b-88c7-7f541ea55a78.JPG)

**Comment by realDunkin** [comment]
You could try to put this https://drive.google.com/file/d/1FUd_qN0RZ2oI74qRcK1xVTG2jWFeDOs7/view?usp=sharing
in `C:\HaxeToolkit\haxe\lib\extension-webm` and then change the text in `.current` to `KadeDev`

**Comment by olderatriangle** [comment]
Am I going to have to do that for every single mod that I compile and port to HTML?

**Comment by realDunkin** [comment]
the extension-webm thing is only one time, as long as you have it there you should be fine

**Comment by olderatriangle** [comment]
How do I change the text in the .current file? I open it and it says "Unable to find software to open this file."

**Comment by realDunkin** [comment]
Right click the `.current` file and then click on `Open With` and then use a text editor, like notepad

**Comment by olderatriangle** [comment]
So like this?
![Capture5](https://user-images.githubusercontent.com/91300048/136867890-eee760c0-589a-4ad8-81c7-a2460c80aa5b.JPG)

**Comment by realDunkin** [comment]
Yeah exactly

**Comment by olderatriangle** [comment]
So I changed it. Do I compile it now?

**Comment by realDunkin** [comment]
Yeah

**Comment by olderatriangle** [comment]
So I tried to build it for Windows, this pops up.
![Capture7](https://user-images.githubusercontent.com/91300048/137055336-c31a19ae-88fe-4bf5-8e6c-1849427e2078.JPG)

**Comment by olderatriangle** [comment]
I try to build it for HTML5, this pops up.
![html error thing](https://user-images.githubusercontent.com/91300048/137055702-36966c07-67b7-4cad-97d8-dedd47b3c8aa.JPG)

**Comment by realDunkin** [comment]
So that where you would go in the code and put something like this 
`#if !htlm5
bla bla bla code that is causing the issue
#end
`

**Comment by olderatriangle** [comment]
I contacted someone, told him the problem and he told me this.
![Screenshot 2021-10-18 8 22 15 PM](https://user-images.githubusercontent.com/91300048/137838612-eac14c81-8273-48af-bc4f-cbde2e900186.png)

**Comment by olderatriangle** [comment]
So I kind of messed up.

**Comment by olderatriangle** [comment]
That was for the Windows thing that I got.

**Comment by realDunkin** [comment]
The camera thing is normal forgot to tell you that

**Comment by olderatriangle** [comment]
So I compiled it, got the camera thing and I waited. 2 hours have passed and nothing happened.

**Comment by realDunkin** [comment]
Thats weird

**Comment by olderatriangle** [comment]
Very weird.

**Comment by olderatriangle** [comment]
Forgot to close this a long time ago.
