### ISSUE TITLE
no issue but uhh just asking

### ISSUE THREAD

**Issue by JDOGGITHUB** [realDunkin/fnfmegapack#31]
Hi there i have been using this project gotta say amazing im happy i found this but can you add new mods like shaggy 2.5 or tricky full week to the less broken version because i cant use the beta considering it just breaks chorme but if you can you maybe give a website to access those mods. 

Thank you for your time and keep up the great work
-JDOG

**Comment by DeceptedPar** [comment]
the beta branches of the game are the experimental versions of the mod, when everything in the beta branch is fixed and ready to go then it'll be moved to the normal branch

**Comment by realDunkin** [comment]
Im also working on improving loading for html5, idk how i can improve it

**Comment by JDOGGITHUB** [comment]
ok thanks for letting me know 
Have a great day
