### ISSUE TITLE
more of a suggestion then a issue 

### ISSUE THREAD

**Issue by ritzable** [realDunkin/fnfmegapack#32]
maybe switch to kade engine instead of mic'd up so it doesn't run up all the ram for computers for the beta version?

**Comment by DeceptedPar** [comment]
while that would be good kade engine at the moment kinda has a memory leak problem.
and also think, customizability and optimization, maybe psych would be better, it's more customizable and also it's easier to do stuff like events in songs, the portability for psych is growing faster than you think

**Comment by ritzable** [comment]
> while that would be good kade engine at the moment kinda has a memory leak problem. and also think, customizability and optimization, maybe psych would be better, it's more customizable and also it's easier to do stuff like events in songs, the portability for psych is growing faster than you think

Hmmm, true
